In [1]:
# week 5 seminar

In [15]:
# 1. 50-100 хүртэл тоон утга бүхий нэг хэмжээст массив (вектор) үүсгэ.

import numpy as np

numbers = np.arange(50, 101)
print(numbers)

[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


In [24]:
# 2. Арван ширхэг 1, арван ширхэг 0, арван ширхэг 6 тоо бүхий нэг хэмжээст массивууд
# (вектор) үүсгэ.

ones = np.ones(10, dtype=int)
zeros = np.zeros(10, dtype=int)
sixes = np.full(10, 6, dtype=int)

result = np.concatenate((ones, zeros, sixes))
print(result)

[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 6 6 6 6 6 6 6 6 6 6]


In [21]:
# 3. 20-32 хүртэл тоон утга бүхий 3x4 хэмжээтэй массив үүсгэ.

numbers1 = np.arange(20, 32)
result = numbers1.reshape(3, 4)
print(result)

[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [33]:
# 4. Диагональ нь 1-ийн тоо, бусад нь 0 байх 3x3 хэмжээтэй массив үүсгэ.

# one = np.array([1], dtype=int)
# zeros = np.zeros(8, dtype=int)

# array = np.concatenate((one, zeros))
# result = array.reshape(3, 3)

################

# array = np.eye(3)

################

# array = np.array([[1, 0, 0],
#                   [0, 1, 0],
#                   [0, 0, 1]])

################
array = np.zeros((3, 3), dtype=int)

for i in range(3):
    array[i, i] = 1

print(array)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [36]:
# 5. Диагональ нь 1-5 хүртэл тоо, бусад нь 0 байх 5х5 хэмжээтэй массив үүсгэ.

array = np.zeros((5, 5), dtype=int)

for i in range(5):
    array[i, i] = i + 1

print(array)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [45]:
# 6. Хоёр хэмжээст массив үүсгэж нийт элементүүдийн нийлбэр, багана, мөрийн
# нийлбэрүүдийг хэвлэ.

array = np.array([1, 2, 3, 4, 5, 6])
array1 = array.reshape(2, 3)
# sum_of_massive = np.sum(array1[0])
# sum_of_column = np.sum(array1[1])

total_sums = np.sum(array1)
column_sums = np.sum(array1, axis=0)
row_sums = np.sum(array1, axis=1)

print(array1)
print("Total Sum:", total_sums)
print("Column Sums:", column_sums)
print("Row Sums:", row_sums)

[[1 2 3]
 [4 5 6]]
Total Sum: 21
Column Sums: [5 7 9]
Row Sums: [ 6 15]


In [63]:
# 7. Спортын сайтуудын мэдээллийг ашиглан хөл бөмбөгийн спортын дурын 10 тоглогчийн
# сүүлийн арван жилийн цалин, нийт тоглолт, оруулсан гоалуудын талаар мэдээллийг
# цуглуулж тус бүрээр массив үүсгэ. Үүсгэсэн массив тус бүрийн багана болон мөрүүдийн
# нийлбэрийг хэвлэ.

# creating dict------------------------
# import random

# football_data = []

# for _ in range(10):
#     player = {
#         'Name': f'Player{_ + 1}',
#         'Salary (in millions USD)': round(random.uniform(1, 10), 2),
#         'Games Played in Year': random.randint(10, 30),
#         'Goals Scored in Year': random.randint(0, 20)
#     }
#     football_data.append(player)

# print(football_data)
# creating dict------------------------

import numpy as np
import random

names = []
salaries = []
games_played = []
goals_scored = []

for i in range(10):
    names.append(f'Player{i + 1}')
    salaries.append(round(random.uniform(1, 10), 2) * 100)
    games_played.append(random.randint(10, 30))
    goals_scored.append(random.randint(0, 20))
    
names_array = np.array(names)
salaries_array = np.array(salaries)
games_played_array = np.array(games_played)
goals_scored_array = np.array(goals_scored)

football_player_data = np.concatenate((salaries_array, games_played_array, goals_scored_array))

result_shaped = football_player_data.reshape(3, 10)
column_sums = np.sum(result_shaped, axis=0)
row_sums = np.sum(result_shaped, axis=1)

print("result_shaped", result_shaped)
print("column_sums", column_sums)
print("row_sums", row_sums)

result_shaped [[605. 888. 743. 675. 555. 765. 974. 282. 838. 113.]
 [ 12.  11.  21.  21.  14.  16.  16.  15.  29.  20.]
 [ 17.  13.   1.  14.  19.  11.   8.   5.  10.  13.]]
column_sums [634. 912. 765. 710. 588. 792. 998. 302. 877. 146.]
row_sums [6438.  175.  111.]
