In [1]:
# Numpy array

import numpy as np

In [3]:
my_list = [1, 2, 3, 4]

my_array = np.array(my_list)
type(my_array)

numpy.ndarray

In [7]:
second_list = [5, 6, 7, 8]

two_d_array = np.array([my_list, second_list])

# type(two_d_array)
print(two_d_array)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
two_d_array.shape

(2, 4)

In [9]:
two_d_array.size

8

In [10]:
two_d_array.dtype

dtype('int32')

In [13]:
# np.identity() to create a square 2d array with 1's across the diagonal
np.identity(n=9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [15]:
np.zeros(shape = [4, 6])


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
# Array indexing and slicing

In [17]:
one_d_array = np.array([1,2,3,4,5,6])
one_d_array[3]

4

In [18]:
one_d_array[3:]

array([4, 5, 6])

In [19]:
one_d_array[::-1]

array([6, 5, 4, 3, 2, 1])

In [20]:
# Create a new 2d array
two_d_array = np.array([one_d_array, one_d_array+6, one_d_array+12])
print(two_d_array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [21]:
# get the element at row index 1, column index 4
two_d_array[1,4]

11

In [26]:
# reverse both dimensions (180 degree rotation)

two_d_array[::-1, ::-1]

array([[18, 17, 16, 15, 14, 13],
       [12, 11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2,  1]])

In [6]:
import numpy as np
my_list = [1, 2, 3, 4]
my_array = np.array(my_list)
two_d_array = np.array([my_array, my_array+6, my_array+12])
print(two_d_array)
two_d_array[1, 3]        

[[ 1  2  3  4]
 [ 7  8  9 10]
 [13 14 15 16]]


10

In [9]:
import copy

original_list = [1, [2, 3]]
shallow_copy = copy.copy(original_list)

shallow_copy[1][0] = 99
print(original_list)
print(shallow_copy)

[1, [99, 3]]
[1, [99, 3]]


In [10]:
import copy

original_list = [1, [2, 3]]
shallow_copy = copy.deepcopy(original_list)

shallow_copy[1][0] = 99
print(original_list)
print(shallow_copy)

[1, [2, 3]]
[1, [99, 3]]


In [12]:
import numpy as np

np.reshape(a=two_d_array, newshape=(4, 3))

array([[ 1,  2,  3],
       [ 4,  7,  8],
       [ 9, 10, 13],
       [14, 15, 16]])

In [13]:
two_d_array.flatten()

array([ 1,  2,  3,  4,  7,  8,  9, 10, 13, 14, 15, 16])

In [14]:
two_d_array.T

array([[ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16]])

In [17]:
np.fliplr(two_d_array)

array([[ 4,  3,  2,  1],
       [10,  9,  8,  7],
       [16, 15, 14, 13]])

In [18]:
np.flipud(two_d_array)

array([[13, 14, 15, 16],
       [ 7,  8,  9, 10],
       [ 1,  2,  3,  4]])

In [19]:
np.rot90(two_d_array, k=1)

array([[ 4, 10, 16],
       [ 3,  9, 15],
       [ 2,  8, 14],
       [ 1,  7, 13]])

In [20]:
array_to_join = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

np.concatenate((two_d_array, array_to_join), axis=1)

array([[ 1,  2,  3,  4, 10, 20, 30],
       [ 7,  8,  9, 10, 40, 50, 60],
       [13, 14, 15, 16, 70, 80, 90]])

In [21]:
two_d_array + 100

array([[101, 102, 103, 104],
       [107, 108, 109, 110],
       [113, 114, 115, 116]])

In [22]:
two_d_array - 100

array([[-99, -98, -97, -96],
       [-93, -92, -91, -90],
       [-87, -86, -85, -84]])

In [23]:
two_d_array * 2

array([[ 2,  4,  6,  8],
       [14, 16, 18, 20],
       [26, 28, 30, 32]])

In [24]:
two_d_array**2

array([[  1,   4,   9,  16],
       [ 49,  64,  81, 100],
       [169, 196, 225, 256]], dtype=int32)

In [25]:
two_d_array%2

array([[1, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0]], dtype=int32)

In [27]:
small_array1 = np.array([[1,2], [3,4]])
small_array1 + small_array1

array([[2, 4],
       [6, 8]])

In [28]:
small_array1 = np.array([[1,2], [3,4]])
small_array1 - small_array1

array([[0, 0],
       [0, 0]])

In [29]:
small_array1 = np.array([[1,2], [3,4]])
small_array1 * small_array1

array([[ 1,  4],
       [ 9, 16]])

In [32]:
small_array1 = np.array([[1,2], [3,4]])
hello = small_array1 ** small_array1
print(hello)

[[  1   4]
 [ 27 256]]


In [43]:
liist = np.array([[1, 2], [3, 4], [5, 6]])
np.mean(liist)
# print(21 / 6)

3.5

In [44]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.dot(a, b)
print(result) #32 (1*4 + 2*5 + 3*6)

32


In [45]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = np.dot(A, B)  # Performs matrix multiplication
print(result) 
# (1 * 5) + (2 * 7) = 5 + 14 = 19
# (1 * 6) + (2 * 8) = 6 + 16 = 22
# (3 * 5) + (4 * 7) = 15 + 28 = 43
# (3 * 6) + (4 * 8) = 18 + 32 = 50


[[19 22]
 [43 50]]


In [46]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])

result1 = np.dot(A, b)  # Matrix-vector multiplication
print(result1)  # Output: [17 39]
# (1 * 5) + (2 * 6) = 5 + 12 = 17
# (3 * 5) + (4 * 6) = 15 + 24 = 39


result2 = np.dot(b, A)  # Vector-matrix multiplication
print(result2)  # Output: [23 34]
# (5 * 1) + (6 * 3) = 5 + 18 = 23
# (5 * 2) + (6 * 4) = 10 + 24 = 34



[17 39]
[23 34]
