In [1]:
# Numpy array

import numpy as np

In [3]:
my_list = [1, 2, 3, 4]

my_array = np.array(my_list)
type(my_array)

numpy.ndarray

In [7]:
second_list = [5, 6, 7, 8]

two_d_array = np.array([my_list, second_list])

# type(two_d_array)
print(two_d_array)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
two_d_array.shape

(2, 4)

In [9]:
two_d_array.size

8

In [10]:
two_d_array.dtype

dtype('int32')

In [13]:
# np.identity() to create a square 2d array with 1's across the diagonal
np.identity(n=9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [15]:
np.zeros(shape = [4, 6])


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
# Array indexing and slicing

In [17]:
one_d_array = np.array([1,2,3,4,5,6])
one_d_array[3]

4

In [18]:
one_d_array[3:]

array([4, 5, 6])

In [19]:
one_d_array[::-1]

array([6, 5, 4, 3, 2, 1])

In [20]:
# Create a new 2d array
two_d_array = np.array([one_d_array, one_d_array+6, one_d_array+12])
print(two_d_array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [21]:
# get the element at row index 1, column index 4
two_d_array[1,4]

11

In [26]:
# reverse both dimensions (180 degree rotation)

two_d_array[::-1, ::-1]

array([[18, 17, 16, 15, 14, 13],
       [12, 11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2,  1]])